### PR TITLE
Switch to NPM only

### PR DESCRIPTION
**Pull request by broerse**
First steps to NPM only. See https://github.com/martndemus/ember-font-awesome/issues/108 
Still 4 tests failing.

### CODE REVIEW

**Comment by josemarluedke** [comment]
Awesome to see this! Any news on finishing and get merged?

**Comment by broerse** [comment]
The Amsterdam Ember Meetup is tomorrow so I hope to talk to @martndemus about it. We need to move only the files specified by the configuration in ember-cli-build.js

**Comment by josemarluedke** [comment]
Ping on this.

Since ember & ember-cli 2.11 is out and ember is now provided by NPM, this is only blocker for us to drop bower from our application.

Do you have an path forward on this?

**Comment by broerse** [comment]
@josemarluedke I know how to fix this and need it myself. Now I have to find time....

**Comment by Panman8201** [comment]
I also just moved another addon to use `ember-cli-node-assets` and would be comfortable making a PR for this one too. @broerse if you don't get to it, let me know and I'll work on it. :)

**Comment by broerse** [comment]
@Panman8201 Please make the PR. I can't find the time now. I think the font awesome dep should be in the addon because the 1:1 relation is more bug-free and requires less code to support all future and past font-awesome versions.

**Comment by broerse** [comment]
Ember 2.0 , 2.1 and 2.2 seem to fail on this PR. i don't mind supporting Ember 2.4 and up only.

**Comment by martndemus** [comment]
@Panman8201 I made you collaborator to this repo, I pay very little attention to this repo, so hoping you can give it a little TLC.

**Comment by martndemus** [comment]
Fixed in #118

**Pull request closed without merging**
