### PR TITLE
upgrade to ember-cli@2.13.2

### PR DESCRIPTION
**Pull request by buschtoens**

### CODE REVIEW

**Comment by buschtoens** [comment]
`ember-lts-2.4` and `ember-lts-2.8` hang indefinitely during building. Not really sure why.

**Comment by buschtoens** [comment]
image

Apparently hanging at `babel-plugin-transform-es2015-block-scoping`.

**Comment by buschtoens** [comment]
Manually changing updating the ember bower dependency resolves this. Apparently that babel transform has issues with these older Ember versions. :thinking:

**Comment by buschtoens** [comment]
Ember v2.10 is the first release that works, so I added it as an ember-try scenario and allowed `lts-2.4` and `lts-2.8` to fail for now.

We'll have to investigate later, what's causing this. Honestly I'm hoping that this problem will magically fix itself one day, when the Babel dependencies receive updates. Debugging this Babel bug is a nightmare. :scream: 

To be clear: we're still compatible with 2.4 and 2.8 and can be consumed by apps running these versions.

@martndemus @Panman8201 @lfridael Any objections or can I go ahead and merge this?

**Comment by snewcomer** [comment]
@buschtoens One option is to leave babel and htmlbars precompile and upgrade everything else.

https://github.com/martndemus/ember-font-awesome/pull/142/files

**Comment by buschtoens** [comment]
@snewcomer Thank you. That's a good idea actually. But I'm doing that for the LTS tests scenarios only, so we can enjoy an up to date build pipeline otherwise. :)

**Pull request merged**
