### PR TITLE
removed less/scss include paths as instructed :+1:

### PR DESCRIPTION
**Pull request by lvl99**
@buschtoens like this?

### CODE REVIEW

**Comment by buschtoens** [comment]
Perfect! Thank you! :)

**Comment by martndemus** [comment]
I'm not sure what's happening here, but this change is already in master:
https://github.com/martndemus/ember-font-awesome/blob/master/index.js#L18

**Comment by buschtoens** [comment]
If you click the blame button in the top right, you can see that 86677179ae2f74d9352a09a749ab0f52c291ea23 already introduced the change :)

**Comment by lvl99** [comment]
👌

**Pull request closed without merging**
