### PR TITLE
Remove explicit references to @glimmer/syntax on transforms

### LINKED ISSUE #185: Cannot find module '@glimmer/syntax' with ember 2.16.2
I was upgrading from 2.15 to the latest ember-cli/ember/-data versions and this error comes up: 
```
Cannot find module '@glimmer/syntax'
Error: Cannot find module '@glimmer/syntax'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mk/PhpstormProjects/larafum/resources/assets/frontend/node_modules/ember-font-awesome/lib/ast-transform.js:4:22)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

### PR DESCRIPTION
**Pull request by cibernox**
It may or may not be enough to fix #185

### CODE REVIEW

**Comment by cibernox** [comment]
@buschtoens ESLint doesn't like the syntax of the new component. How did CI pass on your PR?

**Comment by buschtoens** [comment]
... m.. magic? ✨🔮😅

I'll try to check it out later. Currently on holidays. 🏂

**Comment by buschtoens** [comment]
I wasn't able to reproduce it locally, but maybe this is because ember-try did not `useYarn`? :man_shrugging: 

Anyway #197 runs just fine.

**Comment by buschtoens** [comment]
Did you close this PR intentionally or did GitHub do it? I don't think #197 closes #185. :thinking:

**Comment by cibernox** [comment]
I did not close it. I think the keword "fix #196" triggered this.

**Comment by cibernox** [comment]
It's green now. No idea why.

**Comment by buschtoens** [comment]
> I did not close it. I think the keword "fix #196" triggered this.

Interesting, I just linked the comment and the keyword was not dotted underlined, as it usually is. Seems like we discovered another GitHub bug. :stuck_out_tongue: 

> It's green now. No idea why.

Me neither ¯\_(ツ)_/¯

**Comment by buschtoens** [comment]
Want me to merge and push out an `rc.2`?

**Comment by cibernox** [comment]
That would be great, although I suspect I'll have to make another update to `ember-ast-helpers` to fix this.

**Pull request merged**
