### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by spruce**
This resolves the CI build errors with v3.X .(at least I hope so) I upgraded to the latest ember-cli version and made changes which made sense to me. If anything needs chanings. I'd be happy to change them.

After this #186 and #165 should be able to be green and merged after that.

### CODE REVIEW

**Comment by jrjohnson** [comment]
@spruce thanks for getting this done. Just one change I hope will work.

**Comment by spruce** [comment]
@jrjohnson gonna do it tomorrow. Thanks for the quick response.

**Comment by spruce** [comment]
I don't know why some are failing and others are not. Do you have any idea?

**Comment by jrjohnson** [comment]
Sorry @spruce looks like I sent you down a bad path. I was under the impression that `useYarn` was the fix for the 2.12 scenario failures. If you want to go ahead and remove that last yarn commit I will merge this and we can go forward without yarn here.

**Comment by spruce** [comment]
ok, I removed it again. I'm a little puzzeled as to why bower is not getting installed with yarn ...

**Comment by jrjohnson** [comment]
I think we may not need the framebuffer stuff in travis since testem is using chrome headless, but in the interests of progress I'm going to merge this as is.

**Comment by spruce** [comment]
@jrjohnson could you cut a new release?

**Pull request merged**
