### PR TITLE
fix: enable `{{component "fa-icon" ...}}` usage

### LINKED ISSUE #175: Error when using component helper with "fa-icon"
Hi,

Great addon, super useful.

With `4.0.0-alpha.10`, the following inside a component's template:

```hbs
{{yield (hash icon=(component "fa-icon" currentIcon))}}
```

Results in the following error:

```
Error: Assertion Failed: The component helper cannot be used without a valid component name. You used "fa-icon" via (component "fa-icon")
```

This isn't the case with `3.0.5`.

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #175.

I'll remove the `ember-decorators/argument` type checks, if you want. This is just a straight copy and paste from one of my apps. :stuck_out_tongue: 

I added a `/component` route to the dummy app, to showcase the `{{component "fa-icon" ...}}` invocation.

I hope I added all necessary argument bindings.

I think, this is the most reasonable solution that requires the least amount of hacks. But I'd be happy to see something cleverer, if you got something in mind! :grinning:

### CODE REVIEW

**Comment by buschtoens** [comment]
I should note that there are not tests yet.

**Comment by buschtoens** [comment]
> The output of a `{{component 'fa-icon' selectedIcon}}` is not transformed, but I believe that was the intention.

Yes, indeed. :smile: 

> The only weirdness I saw is that the `{{component 'fa-icon' selectedIcon}}` invocation yields HTML like `<i class='fa fa-1x fa-calendar fa-pull- fa-rotate-0 fa-flip-'>` with extra `fa-pull-`, `fa-slip-` and `fa-rotate-0` classes.

Good catch! I'll fix that.

**Comment by cibernox** [comment]
The main problem with this, is that the addon won't be 100% runtime anymore, which is what v4 wanted to achieve. I'd love to know if there is a way to conditionally include this runtime component.

**Comment by buschtoens** [comment]
> conditionally

Depending on what? We could add a build option (`includeRuntimeComponent`, kind alike `includeStaticIcons`), that removes the component from the addon tree, if `false`.

Automatically detecting `{{component "fa-icon"}}` is a bad idea IMHO, since users might also pass the component name as a variable.

**Comment by cibernox** [comment]
Yeah, I mean with a configuration option, disabled by default, but with
clear instructions on how to enable it.

2017-12-01 16:34 GMT+01:00 Jan Buschtöns <notifications@github.com>:

**Comment by buschtoens** [comment]
Cool. I'll add that.

**Comment by buschtoens** [comment]
Regarding the extra CSS classes, there isn't much I can do to solve it in this addon. If the attrs are passed to the component invocation, `ember-ast-helpers` adds the classes. Since I can't conditionally pass attrs, this would require a change in `ember-ast-helpers`.

**Comment by cibernox** [comment]
I'll re-read this tomorrow to see if there's something I can do in AST helpers to avoid extra classes, but I'm not sure I can.

**Comment by jrjohnson** [comment]
@cibernox if there isn't anything to be done about the extra classes I support merging this as is to move us closer to getting v4 tagged.

**Comment by cibernox** [comment]
Sorry, I forgot. No, there isn't really anything I can do myself to make the output better. On the bright side, those classes add noise but they are innocuous. However I remember that @buschtoens mentioned he was adding a flag to make this runtime component an opt in, so the addon by default adds no JS code.

**Comment by buschtoens** [comment]
> @buschtoens mentioned he was adding a flag to make this runtime component an opt in, so the addon by default adds no JS code.

Yeah sorry,. Maybe I can finally get around to it today. :)

**Comment by buschtoens** [comment]
Users now have to explicitly opt-in via the `includeComponent` option. If not enabled, no files are added to the host app.

**Comment by cibernox** [comment]
It looks great.

**Pull request merged**
