### PR TITLE
Assume `otherAssetPaths` can be undefined

### PR DESCRIPTION
**Pull request by spruce**
Cherry picking commit from master onto v3.X.

(could you do a release right after this? 👍 )

### CODE REVIEW

**Comment by spruce** [comment]
Hey @jrjohnson ,
here is the PR mentioned in https://github.com/martndemus/ember-font-awesome/commit/07c498827cec52863ec37411e11c6db66ab94bff#commitcomment-25416985
Two things remain for me, which I tried to fix (maybe next PR?):
1. Creates only same errors as previous PR: https://github.com/martndemus/ember-font-awesome/pull/148 
2. Should this be fixed for the v3.X or is it okay that it only works on master for now

**Comment by jrjohnson** [comment]
Thanks @spruce. I'm going to attempt to fix the tests in the 3.x branch tomorrow so we can unblock this (as well as my #165). If I can't get that done tomorrow we may be able to merge this as is.

**Comment by spruce** [comment]
We had some of the same issues. Especially regarding 2.12. I don't know whether that helps but this was our solution: https://github.com/piceaTech/ember-rapid-forms/pull/175/commits/e248c9bfc424d2cf0651b15218e1ab894f2ee4d9
also maybe this might help: https://github.com/piceaTech/ember-rapid-forms/pull/175/commits/d4adf3125fbda6a1ffcf5f700226d07d7febbe48

**Comment by spruce** [comment]
@jrjohnson Could you restart the tests for this and maybe merge this? + releasing a new v3.x version. I have a dependency on it and need it. Thanks 👍

**Comment by jrjohnson** [comment]
@spruce - I restarted tests, but that didn't help. This needs to be rebased.

**Comment by spruce** [comment]
@jrjohnson sorry, my bad. I now rebases and pushed the rebased commit. Hopefully tests should pass now.

**Pull request merged**
